name: Build and Deploy Infro
on: [workflow_dispatch]
env:
  GO_VERSION: 1.20.1
  
jobs: 
  build-infra:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: test get-function
        run: cd get-function && go test -v ./ && cd ../../
      - name: test put-function
        run: cd put-function && go test -v ./ && cd ../../

  build-and-deploy-infra:
    needs: build-infra
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - run: sam build
        working-directory: ./
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
        working-directory: ./

