name: Build Infra
on: [workflow_dispatch]
env:
  GO_VERSION: 1.20.1
  
jobs: 
  build-infra:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: test get-function
        run: cd get-function && go test -v ./ && cd ../../
      - name: test put-function
        run: cd put-function && go test -v ./ && cd ../../

  
